 jobs:
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh deployment@178.128.251.71 "/home/deployment/test.sh"

 workflows:
   version: 2
   build-and-deploy:
     jobs:
       - deploy:
