 jobs:
   deploy:
     machine:
       enabled: true
     steps:
       - add_ssh_keys:
          fingerprints:
            - "55:20:fe:22:09:e0:0b:12:2f:d9:16:91:cb:5f:74:d2"
       - run:
           name: Deploy Over SSH
           command: |
             ssh deployment@178.128.251.71 "/home/deployment/test.sh"

 workflows:
   version: 2
   build-and-deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: circleci-project-setup
